[GLOBAL]
plugins.add = ["shoalsoft-pants-opentelemetry-plugin==0.2.1"]
backend_packages.add = ["shoalsoft.pants_opentelemetry_plugin"]
print_stacktrace = true
level = "DEBUG"
log_show_rust_3rdparty = true

[shoalsoft-opentelemetry]
enabled = true
exporter = "grpc"
exporter_endpoint = "https://api.honeycomb.io"

[shoalsoft-opentelemetry.exporter_headers]
"x-honeycomb-team" = "%(env.HONEYCOMB_API_KEY)s"

