[GLOBAL]
pants_version = "2.32.1"
backend_packages.add = [
  "pants.backend.build_files.fmt.black",
  "pants.backend.plugin_development",
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
]

[python]
interpreter_constraints = ["==3.14.*"]
interpreter_versions_universe = ["3.14"]
enable_resolves = true
pip_version = "latest"
default_resolve = "pants-2.32"

[python.resolves]
"pants-2.32" = "3rdparty/python/pants-2.32.lock"
pytest = "3rdparty/python/pytest.lock"
mypy = "3rdparty/python/mypy.lock"

[python.resolves_to_interpreter_constraints]
"pants-2.32" = ["==3.14.*"]

[python-bootstrap]
search_path = ["<PYENV>"]

[python-infer]
unowned_dependency_behavior = "error"

[python-repos]
find_links = ["https://wheels.pantsbuild.org/simple"]

[pex-cli]
version = "v2.96.1"
known_versions = [
  "v2.96.1|macos_arm64|fcb10c5c0f560bb6c5e072f88dcee5123690d5b2aef4e76d75caed733101378b|5040040",
  "v2.96.1|macos_x86_64|fcb10c5c0f560bb6c5e072f88dcee5123690d5b2aef4e76d75caed733101378b|5040040",
  "v2.96.1|linux_x86_64|fcb10c5c0f560bb6c5e072f88dcee5123690d5b2aef4e76d75caed733101378b|5040040",
  "v2.96.1|linux_arm64|fcb10c5c0f560bb6c5e072f88dcee5123690d5b2aef4e76d75caed733101378b|5040040",
]

[pytest]
args = ["--no-header", "-vv"]
install_from_resolve = "pytest"
requirements = ["//3rdparty/python:pytest"]

[mypy]
install_from_resolve = "mypy"

[source]
root_patterns = ["/src/python"]

[anonymous-telemetry]
enabled = false

[flake8]
config = "build-support/flake8/.flake8"
