[GLOBAL]
plugins.add = ["shoalsoft-pants-opentelemetry-plugin==0.5.0.dev0"]
backend_packages.add = ["shoalsoft.pants_opentelemetry_plugin"]

[shoalsoft-opentelemetry]
enabled = true
exporter_endpoint = "https://api.honeycomb.io"
trace_link_template = "https://ui.honeycomb.io/shoalsoft/environments/shoalsoft-pants-opentelemetry-plugin/trace?trace_id={trace_id}&span={root_span_id}"

[shoalsoft-opentelemetry.exporter_headers]
"x-honeycomb-team" = "%(env.HONEYCOMB_API_KEY)s"
