[GLOBAL]
plugins.add = ["shoalsoft-pants-opentelemetry-plugin==0.3.1.dev1"]
backend_packages.add = ["shoalsoft.pants_opentelemetry_plugin"]
level = "debug"

[shoalsoft-opentelemetry]
enabled = true
exporter = "http"
exporter_endpoint = "https://api.honeycomb.io:443"
async_completion = false

[shoalsoft-opentelemetry.exporter_headers]
"x-honeycomb-team" = "%(env.HONEYCOMB_API_KEY)s"
