[GLOBAL]
pythonpath.add = ["%(buildroot)s/src/python"]
backend_packages.add = ["shoalsoft.pants_opentelemetry_plugin"]
print_stacktrace = true
level = "debug"
log_show_rust_3rdparty = true
pantsd = false

[shoalsoft-opentelemetry]
enabled = true
exporter = "http"
exporter_endpoint = "https://api.honeycomb.io:443"
async_completion = false

[shoalsoft-opentelemetry.exporter_headers]
"x-honeycomb-team" = "%(env.HONEYCOMB_API_KEY)s"

