[GLOBAL]
plugins.add = ["shoalsoft-pants-opentelemetry-plugin==0.3.1.dev0"]
backend_packages.add = ["shoalsoft.pants_opentelemetry_plugin"]
level = "debug"

[python-repos]
indexes = ["https://test.pypi.org/simple/"]

[shoalsoft-opentelemetry]
enabled = true
exporter = "grpc"
exporter_endpoint = "https://api.honeycomb.io"
async_completion = false

[shoalsoft-opentelemetry.exporter_headers]
"x-honeycomb-team" = "%(env.HONEYCOMB_API_KEY)s"
